POST http://localhost:8080/login/username-pwd
Content-Type: application/json

{
  "username": 1,
  "password": 1
}


###
GET http://localhost:8080/user/detail/1

###
GET http://localhost:8080/user/exception

###
GET http://localhost:8080/user/1exception