POST http://localhost:8080/template-dubbo-web/login/username-pwd
Content-Type: application/json

{
  "username": 1,
  "password": 1
}


###
GET http://localhost:8080/template-dubbo-web/user/detail/1

###
GET http://localhost:8080/template-dubbo-web/user/exception

###
GET http://localhost:8080/template-dubbo-web/user/1exception