GET http://localhost:8080/demo/test
Content-Type: application/json

{
  "data": "eyJ0aXRsZSI6IuWGhemDqOS4muWKoS3mtYvor5Xnjq/looPph43lkK8tMjAyMzA3MTgtMS3mtYvor5UiLCJ0eXBlIjoiUkVTVEFSVCJ9"
}

###
GET http://localhost:8080/demo/exception
Content-Type: application/json

{
  "data": "eyJ0aXRsZSI6IuWGhemDqOS4muWKoS3mtYvor5Xnjq/looPph43lkK8tMjAyMzA3MTgtMS3mtYvor5UiLCJ0eXBlIjoiUkVTVEFSVCJ9"
}


###
GET http://localhost:8080/template-dubbo-web/user/detail/1

###
GET http://localhost:8080/template-dubbo-web/user/exception

###
GET http://localhost:8080/template-dubbo-web/user/1exception